name: run script on rds

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: run script on rds
      run: |
        mysql --protocol=tcp -h ${{ secrets.AWS_DB_INSTANCE }} -P 3306 -uroot -p${{ secrets.AWS_DB_PASSWORD }} -e "./database/init.sql"